### ISSUE TITLE
Weird error when fetching from JIRA

### ISSUE THREAD

**Issue by gusblack-tt** [github/ghas-jira-integration#45]
Hello we are trying to get this setup for our repo and seeing this error

```
DEBUG:urllib3.connectionpool:[https://tranecortex.atlassian.net:443](https://tranecortex.atlassian.net/) "GET /rest/api/2/search?jql=project%3D%22DWA%22+and+description+~+%22290af322f9cb4b0a321b692b164f150b157f047a83168febf076db55717ab1de%22&startAt=0&validateQuery=True HTTP/1.1" 400 None
Traceback (most recent call last):
  File "/home/runner/work/_actions/github/ghas-jira-integration/v1/cli.py", line 321, in <module>
    main()
  File "/home/runner/work/_actions/github/ghas-jira-integration/v1/cli.py", line 318, in main
    args.func(args)
  File "/home/runner/work/_actions/github/ghas-jira-integration/v1/cli.py", line 104, in sync
    s.sync_repo(repo_id, states=state)
  File "/home/runner/work/_actions/github/ghas-jira-integration/v1/sync.py", line 115, in sync_repo
    for i in self.jira.fetch_issues(repo.get_key()):
  File "/home/runner/work/_actions/github/ghas-jira-integration/v1/jiralib.py", line 221, in fetch_issues
    for raw in self.j.search_issues(issue_search, maxResults=0)
  File "/home/runner/.local/lib/python3.8/site-packages/jira/client.py", line 2523, in search_issues
    issues = self._fetch_pages(
  File "/home/runner/.local/lib/python3.8/site-packages/jira/client.py", line 636, in _fetch_pages
    resource = self._get_json(request_path, params=page_params, base=base)
  File "/home/runner/.local/lib/python3.8/site-packages/jira/client.py", line 3139, in _get_json
    r = self._session.get(url, params=params)
  File "/home/runner/.local/lib/python3.8/site-packages/jira/resilientsession.py", line 172, in get
    return self.__verb("GET", url, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/jira/resilientsession.py", line 168, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/jira/resilientsession.py", line 53, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://tranecortex.atlassian.net/rest/api/2/search?jql=project%3D%22DWA%22+and+description+~+%22290af322f9cb4b0a321b692b164f150b157f047a[83](https://github.com/nexiahome/nexia_dealer/runs/7568634532?check_suite_focus=true#step:2:85)168febf076db55717ab1de%22&startAt=0&validateQuery=True
	text: The value 'DWA' does not exist for the field 'project'.
	
	response headers = {'Date': 'Thu, 28 Jul 2022 21:02:49 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Server': 'globaledge-envoy', 'Timing-Allow-Origin': '*', 'X-Arequestid': 'cdcb4620-33a4-487d-9b33-0a397e3d4cf3', 'Cache-Control': 'no-cache, no-store, no-transform', 'X-Envoy-Upstream-Service-Time': '66', 'Expect-Ct': 'report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/atlassian-proxy", max-age=86400', 'Strict-Transport-Security': 'max-age=63072000; preload', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Atl-Traceid': '0ba9a73c174f24[85](https://github.com/nexiahome/nexia_dealer/runs/7568634532?check_suite_focus=true#step:2:87)', 'Report-To': '{"group": "endpoint-1", "max_age": 600, "endpoints": [{"url": "https://dz8aopenkvv6s.cloudfront.net/"}], "include_subdomains": true}', 'Nel': '{"report_to": "endpoint-1", "max_age": 600, "include_subdomains": true, "failure_fraction": 0.001}', 'Transfer-Encoding': 'chunked'}
	response text = {"errorMessages":["The value 'DWA' does not exist for the field 'project'.","Field 'description' does not exist or this field cannot be viewed by anonymous users."],"warningMessages":[]}
Error: Process completed with exit code 1.
```

Our configuration looks as follows:
```

name: "Sync GHAS to Jira"

on:
  workflow_dispatch:
  # schedule:
    # - cron: '*/9 * * * *'    # trigger synchronization every 9 minutes

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://tranecortex.atlassian.net'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'DVSCPS'
          github_token: '${{ secrets.GH_TO_JIRA_SEC_TOKEN }}'
          sync_direction: 'gh2jira'
```

**Comment by mwiggPI** [comment]
+1, experiencing this error also, seems to be related to session not being created?

**Comment by mwiggPI** [comment]
I realized that the reason I was experiencing this issue was because the Jira username/API token combo I'd entered weren't correct. Once I went from using account ID to actual username it worked.

**Comment by gusblack-tt** [comment]
> I realized that the reason I was experiencing this issue was because the Jira username/API token combo I'd entered weren't correct. Once I went from using account ID to actual username it worked.

Forgot to respond but my issue was the same exact thing as well. :)
